volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'
      - '--web.config.file=/etc/prometheus/web.yml'
    restart: unless-stopped
    ports:
      - 9100:9090

  nodeexporter:
    image: prom/node-exporter:v1.8.2
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9101:9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    ports:
      - 9108:8080

  pushgateway:
    image: prom/pushgateway:v1.10.0
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9103:9091

  clamav-prometheus-exporter:
    image: rekzi/clamav-prometheus-exporter:latest
    command:
      - '--clamav-address=clamd-aocc8s440kggg8ow80g80c4o'
    ports:
      - 9104:9810

  loki:
    image: grafana/loki:2.9.10
    hostname: loki
    container_name: loki
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3199:3100"
    restart: unless-stopped
    user: 1000:1000
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    depends_on:
      - loki
    hostname: promtail
    ports:
      - 9080:9080
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
      - /data/coolify/logs:/var/log/traefik
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
