{
 "title": "ClamAV Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Prometheus", "query": "prometheus" },
   { "name": "instance", "query": { "query": "clamav_build_info" } }
  ]
 },
 "panels": [
  { "title": "Global Pool Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue Length",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(clamav_queue_length)" }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamav_threads_live) / sum(clamav_threads_max) * 100"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(clamav_mem_used_bytes) / sum(clamav_mem_heap_bytes) * 100"
    }
   ]
  },
  {
   "title": "Build Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "clamav_build_info" }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "instance" },
  {
   "title": "Queue Length",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamav_queue_length{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamav_mem_used_bytes{instance=\"$instance\"} / clamav_mem_heap_bytes{instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clamav_threads_live{instance=\"$instance\"} / clamav_threads_max{instance=\"$instance\"} * 100"
    }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamav_threads_max{instance=\"$instance\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "clamav_threads_live{instance=\"$instance\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "clamav_threads_idle{instance=\"$instance\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "clamav_queue_length{instance=\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Memory Detailed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "clamav_mem_heap_bytes{instance=\"$instance\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "clamav_mem_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "clamav_mem_mmap_bytes{instance=\"$instance\"}",
     "legendFormat": "mmap"
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "clamav_pools_total_bytes{instance=\"$instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "clamav_pools_used_bytes{instance=\"$instance\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}